#!/usr/bin/env python3
# ===========================================================================
# cliproxy_seam_extract.py — value-free extraction of the collector's
# cooldown/publication seam (source-export method v3)
#
# WHY THIS EXISTS
#
# Method v2 recovered the host collector (`cliproxy_usage_snapshot.py`,
# 57,397 B) by whole-file HUMAN inspection and a browser upload. On
# 2026-09-26 the operator withheld it: the operator role is an AI-assisted
# session, so "inspect the whole file locally" would put raw, possibly
# credential-bearing source into a transcript. No human executor exists.
#
# v3 moves the safety property from a person's eyes into this reviewed tool:
#
#   * the source is PARSED (ast.parse) — never imported, compiled to bytecode
#     or executed; the raw bytes are never copied, printed or written;
#   * only a narrow slice is emitted: the anchor functions around
#     `_attach_cooldowns`, the module-level helpers/constants they reach, and
#     the top-level tail from the first anchor call to end of file (the
#     publication seam). Everything else — fetchers, auth handling — is
#     dropped, and only its NAME is listed in the manifest if referenced;
#   * the slice is re-rendered with ast.unparse, which drops every comment;
#     docstrings are removed;
#   * every str literal is kept only if it passes a fail-closed allowlist
#     (short, printable, no secret-shaped run); otherwise it becomes
#     "<redacted:str:len=N>". bytes literals are always redacted; ints longer
#     than 12 digits become the name _REDACTED_INT;
#   * any identifier that looks secret-shaped REFUSES the run (renaming would
#     change semantics silently);
#   * the rendered output is re-scanned with the same detectors; any hit
#     deletes it and refuses.
#
# stdout carries ONLY a value-free JSON manifest (hashes, counts, line
# ranges, extracted names). It is safe to land in an operator transcript.
#
# Exit codes: 0 extracted; 2 REFUSED (nothing written, reason on stderr).
# Requires Python >= 3.9 (ast.unparse). Run as: python3 -I -B <this> ...
# ===========================================================================
import argparse
import ast
import hashlib
import json
import os
import re
import stat
import sys

ANCHORS = ("_attach_cooldowns", "_apply_health_floor", "_mark_unobserved")
MAX_STR = 96
MAX_INT_DIGITS = 12
BANNER = (
    "# REVIEW-ONLY EXTRACT — not the collector, not executable as deployed.\n"
    "# Generated by cliproxy_seam_extract.py (source-export method v3) from a\n"
    "# fingerprint-verified source. Comments/docstrings dropped; literals that\n"
    "# fail the allowlist are shown as <redacted:...>. Do not run or import.\n"
)

# Secret-shape detectors. Deliberately over-broad: a false positive costs a
# redacted literal (or a refusal); a false negative costs a leaked credential.
_DETECTORS = (
    ("token_prefix", re.compile(
        r"(?:sk-|sk_|ghp_|gho_|ghs_|ghu_|ghr_|github_pat_|xox[abprs]-|AKIA|ASIA|eyJ|"
        r"glpat-|hf_|AIza|Bearer\s|Basic\s)")),
    ("hex_run", re.compile(r"[0-9a-fA-F]{16,}")),
    ("dense_run", re.compile(r"[A-Za-z0-9+/=_\-]{20,}")),
    ("email", re.compile(r"[A-Za-z0-9._%+\-]+@[A-Za-z0-9\-]+(?:\.[A-Za-z0-9\-]+)*\.[A-Za-z]{2,}")),
    ("url_userinfo", re.compile(r"://[^/\s:@]+:[^/\s@]+@")),
    ("pem", re.compile(r"-----BEGIN")),
)
_PRINTABLE = re.compile(r"^[\x20-\x7e]*$")


class Refused(Exception):
    pass


def _hits(text):
    out = []
    for name, rx in _DETECTORS:
        for m in rx.finditer(text):
            s = m.group(0)
            # A dense run that is purely letters/underscores is an identifier
            # or a word, not a credential; require a digit AND a letter.
            if name == "dense_run" and not (re.search(r"\d", s) and re.search(r"[A-Za-z]", s)):
                continue
            out.append(name)
    return out


def literal_allowed(s):
    return len(s) <= MAX_STR and bool(_PRINTABLE.match(s)) and not _hits(s)


def _sha(b):
    return hashlib.sha256(b).hexdigest()


def read_verified(path, sha256, size, newlines):
    """Open with O_NOFOLLOW, require a regular file under non-symlink parents,
    and match the pinned fingerprint. Returns the bytes (kept in memory)."""
    real_parent = os.path.dirname(os.path.abspath(path))
    probe = real_parent
    while probe and probe != os.path.dirname(probe):
        if os.path.islink(probe):
            raise Refused("parent directory is a symlink")
        probe = os.path.dirname(probe)
    try:
        fd = os.open(path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
    except OSError as e:
        raise Refused(f"cannot open source without following links ({e.errno})")
    try:
        st = os.fstat(fd)
        if not stat.S_ISREG(st.st_mode):
            raise Refused("source is not a regular file")
        chunks = []
        while True:
            c = os.read(fd, 65536)
            if not c:
                break
            chunks.append(c)
    finally:
        os.close(fd)
    data = b"".join(chunks)
    got = {"sha256": _sha(data), "bytes": len(data), "newlines": data.count(b"\n")}
    want = {"sha256": sha256, "bytes": size, "newlines": newlines}
    if got != want:
        drift = sorted(k for k in want if got[k] != want[k])
        raise Refused("baseline mismatch on " + ",".join(drift))
    return data


def _names_in(node):
    # Bare names only: `x.get` must not pull in a module-level def named get.
    return {n.id for n in ast.walk(node) if isinstance(n, ast.Name)}


def _assigned_names(stmt):
    targets = []
    if isinstance(stmt, ast.Assign):
        targets = stmt.targets
    elif isinstance(stmt, (ast.AnnAssign, ast.AugAssign)):
        targets = [stmt.target]
    out = set()
    for t in targets:
        out |= {n.id for n in ast.walk(t) if isinstance(n, ast.Name)}
    return out


def select(tree):
    """Pick the anchor defs, their module-level closure, and the tail."""
    body = tree.body
    defs = {}
    for i, st in enumerate(body):
        if isinstance(st, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if st.name in defs:
                raise Refused(f"duplicate top-level definition of {st.name}")
            defs[st.name] = i
    missing = [a for a in ANCHORS if a not in defs]
    if missing:
        raise Refused("anchor not found: " + ",".join(missing))

    tail_start = None
    for i, st in enumerate(body):
        if isinstance(st, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            continue
        calls = {n.func.id for n in ast.walk(st)
                 if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)}
        if calls & set(ANCHORS):
            tail_start = i
            break
    if tail_start is None:
        raise Refused("no top-level statement calls an anchor")

    assigns = {}
    for i, st in enumerate(body[:tail_start]):
        for name in _assigned_names(st):
            assigns.setdefault(name, []).append(i)

    chosen = set(defs[a] for a in ANCHORS) | set(range(tail_start, len(body)))
    referenced_only = set()
    frontier = list(chosen)
    seen = set()
    while frontier:
        i = frontier.pop()
        if i in seen:
            continue
        seen.add(i)
        for name in _names_in(body[i]):
            if name in defs and defs[name] < tail_start and defs[name] not in chosen:
                # A reachable module-level helper ships whole; its literals
                # still go through the redactor like everything else.
                chosen.add(defs[name])
                frontier.append(defs[name])
            elif name in assigns:
                for j in assigns[name]:
                    st = body[j]
                    if j not in chosen and _is_constant_assign(st):
                        chosen.add(j)
                        frontier.append(j)
                    elif j not in chosen:
                        referenced_only.add(name)
    return sorted(chosen), tail_start, referenced_only


def _is_constant_assign(st):
    """A module-level assignment whose value is a literal container/constant
    (or a reference-free expression). Assignments that call anything are not
    shipped — their NAME is listed instead."""
    value = getattr(st, "value", None)
    if value is None:
        return False
    return not any(isinstance(n, (ast.Call, ast.Await, ast.Lambda)) for n in ast.walk(value))


class _Redactor(ast.NodeTransformer):
    def __init__(self):
        self.str_kept = 0
        self.str_redacted = 0
        self.bytes_redacted = 0
        self.int_redacted = 0
        self.docstrings_dropped = 0

    def _strip_docstring(self, node):
        b = getattr(node, "body", None)
        if (b and isinstance(b[0], ast.Expr) and isinstance(b[0].value, ast.Constant)
                and isinstance(b[0].value.value, str)):
            self.docstrings_dropped += 1
            node.body = b[1:] or [ast.Pass()]

    def visit_FunctionDef(self, node):
        self._strip_docstring(node)
        return self.generic_visit(node)

    visit_AsyncFunctionDef = visit_FunctionDef
    visit_ClassDef = visit_FunctionDef

    def visit_Constant(self, node):
        v = node.value
        if isinstance(v, bool) or v is None or v is Ellipsis:
            return node
        if isinstance(v, str):
            if literal_allowed(v):
                self.str_kept += 1
                return node
            self.str_redacted += 1
            return ast.copy_location(ast.Constant(f"<redacted:str:len={len(v)}>"), node)
        if isinstance(v, bytes):
            self.bytes_redacted += 1
            return ast.copy_location(ast.Constant(f"<redacted:bytes:len={len(v)}>"), node)
        if isinstance(v, int):
            if len(str(abs(v))) > MAX_INT_DIGITS:
                self.int_redacted += 1
                return ast.copy_location(ast.Name("_REDACTED_INT", ast.Load()), node)
            return node
        if isinstance(v, (float, complex)):
            return node
        self.str_redacted += 1
        return ast.copy_location(ast.Constant("<redacted:other>"), node)


def _check_identifiers(nodes):
    for root in nodes:
        for n in ast.walk(root):
            ident = None
            if isinstance(n, ast.Name):
                ident = n.id
            elif isinstance(n, ast.Attribute):
                ident = n.attr
            elif isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                ident = n.name
            elif isinstance(n, ast.arg):
                ident = n.arg
            elif isinstance(n, ast.keyword) and n.arg:
                ident = n.arg
            elif isinstance(n, ast.alias):
                ident = n.asname or n.name
            if ident and _hits(ident):
                raise Refused("secret-shaped identifier in the extracted slice")


def extract(data):
    if sys.version_info < (3, 9):
        raise Refused("python >= 3.9 required for ast.unparse")
    try:
        src = data.decode("utf-8")
    except UnicodeDecodeError:
        raise Refused("source is not valid UTF-8")
    try:
        tree = ast.parse(src, filename="<collector>", mode="exec")
    except SyntaxError as e:
        raise Refused(f"source does not parse (line {e.lineno})")
    chosen, tail_start, referenced_only = select(tree)
    nodes = [tree.body[i] for i in chosen]
    _check_identifiers(nodes)
    ranges = [{"kind": type(n).__name__,
               "name": getattr(n, "name", None),
               "lines": [n.lineno, n.end_lineno]} for n in nodes]
    red = _Redactor()
    nodes = [red.visit(n) for n in nodes]
    mod = ast.Module(body=nodes, type_ignores=[])
    ast.fix_missing_locations(mod)
    rendered = BANNER + ast.unparse(mod) + "\n"
    if _hits(rendered.replace(BANNER, "")):
        raise Refused("rendered extract still matches a secret detector")
    selected_names = {r["name"] for r in ranges if r["name"]}
    manifest = {
        "method": "source-export v3 (AST seam extraction)",
        "anchors": list(ANCHORS),
        "tail_first_line": tree.body[tail_start].lineno,
        "segments": ranges,
        "referenced_not_shipped": sorted(referenced_only - selected_names),
        "counts": {"str_kept": red.str_kept, "str_redacted": red.str_redacted,
                   "bytes_redacted": red.bytes_redacted, "int_redacted": red.int_redacted,
                   "docstrings_dropped": red.docstrings_dropped,
                   "source_top_level_statements": len(tree.body),
                   "extracted_top_level_statements": len(nodes)},
    }
    return rendered, manifest


def write_private(path, text):
    parent = os.path.dirname(os.path.abspath(path))
    st = os.lstat(parent)
    if not stat.S_ISDIR(st.st_mode) or stat.S_IMODE(st.st_mode) & 0o077:
        raise Refused("output directory must be a real directory with mode 0700")
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0), 0o600)
    try:
        os.write(fd, text.encode("utf-8"))
    finally:
        os.close(fd)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", required=True)
    ap.add_argument("--expect-sha256", required=True)
    ap.add_argument("--expect-bytes", required=True, type=int)
    ap.add_argument("--expect-newlines", required=True, type=int)
    ap.add_argument("--output", required=True,
                    help="new file in a 0700 directory; must not exist")
    a = ap.parse_args(argv)
    try:
        if os.path.lexists(a.output):
            raise Refused("output path already exists")
        data = read_verified(a.source, a.expect_sha256, a.expect_bytes, a.expect_newlines)
        rendered, manifest = extract(data)
        del data
        write_private(a.output, rendered)
    except Refused as e:
        print(f"REFUSED: {e}", file=sys.stderr)
        return 2
    out = rendered.encode("utf-8")
    manifest["source"] = {"sha256": a.expect_sha256, "bytes": a.expect_bytes,
                          "newlines": a.expect_newlines, "verified": True}
    manifest["extract"] = {"sha256": _sha(out), "bytes": len(out),
                           "newlines": out.count(b"\n")}
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
